name: 'Event Transformer'
description: 'Templating on the go'
author: 'anuraag016'
inputs:
  accessToken:
    description: 'access token available in the workflow file to authenticate call to github api'
    default: ${{ github.token }}
  repoName:
    description: 'input repo for templates here'
    required: false
    default: 'github/chat-templates'
  branchName:
    description: 'branch name here'
    required: false
    default: 'main'
  data:
    description: 'input data to use for rendering'
    required: true
    default: '{}'
  templateType:
    description: 'template type to use ex. HandleBars, Liquid'
    required: false
    default: 'HandleBars'
  sourceType:
    description: 'source type as mentioned in the template config for the template'
    required: true
  clientType:
    description: 'client type can be null to indicate event transformer'
    required: false
    default: 'Slack'
runs:
  using: 'node12'
  main: 'dist/index.js'
